#JSON KEYS FOR EXCHANGING DATA
KEY_CIPHERED_SYMM_KEY           = "ciphered_symm_key"
KEY_CIPHERED_CONTENT            = "ciphered_content"

#GENERIC
BUFFER_SIZE_CLIENT              = 65520
BUFFER_SIZE_SERVER              = 65520
SERVER_PORT                     = 3000
TABLE_NUMBER_OF_PLAYERS         = 4  
CARDS_IN_HAND                   = 13
SOCKET_TIMEOUT                  = .8
SOCKET_IDLE_LIMIT               = 500
PERCENTAGE_CHANCE               = 90
PERCENTAGE_CHEAT                = 10
DEBUG_MODE                      = False
AUTO_PLAY                       = False
USE_CC                          = False
USE_AESCBC                      = True
USE_AESOFB                      = False
USE_AESCFB                      = False

#SERVER TO CLIENT
SEND_PUBLIC_KEY                 = "SEND_PUBLIC_KEY"
WAIT                            = "WAIT"
NO_PENDING_ACTIONS              = "NO_PENDING_ACTIONS"
SHUFFLE_DECK                    = "SHUFFLE_DECK"
SHARE_PUB_KEYS                  = "SHARE_PUB_KEYS"
DECK_DISTRIBUTION               = "DECK_DISTRIBUTION"
BIT_COMMITMENT                  = "BIT_COMMITMENT"
SHARE_CARDS_CYPHER_KEY          = "SHARE_CARDS_CYPHER_KEY"
DECRYPT_HAND                    = "DECRYPT_HAND"
PLAY_CARD                       = "PLAY_CARD"
GAME_OVER                       = "GAME_OVER"
ASK_JOIN_TABLE                  = "ASK_JOIN_TABLE"
UPDATE_CURRENT_HAND             = "UPDATE_CURRENT_HAND"
COMPLAIN_SENT                   = "COMPLAIN_SENT"


#CLIENT TO SERVER 
LOGIN                           = "LOGIN"
EXCHANGE_PUBLIC_KEYS            = "EXCHANGE_PUBLIC_KEYS"
CHECK_PENDING_ACTIONS           = "CHECK_PENDING_ACTIONS"
SEND_DECK_TO_NEXT_PLAYER        = "SEND_DECK_TO_NEXT_PLAYER"
ACK_PUBLIC_KEYS                 = "ACK_PUBLIC_KEYS"
DECK_SHUFFLED                   = "DECK_SHUFFLED"
DECK_DISTRIBUTED                = "DECK_DISTRIBUTED"
ACK_BIT_COMMITMENT              = "ACK_BIT_COMMITMENT"
ACK_DECK_CYPHER_KEY             = "ACK_DECK_CYPHER_KEY"
ACK_DECRYPT_HAND                = "DECRYPT_HAND"
CARD_PLAYED                     = "CARD_PLAYED"
JOIN_TABLE                      = "JOIN_TABLE"
HAND_UPDATED                    = "HAND_UPDATED"
COMPLAIN                        = "COMPLAIN"
ACK_COMPLAIN                    = "ACK_COMPLAIN"


KEY_CIPHERED_CONTENT            = "KEY_CIPHERED_CONTENT" 
KEY_CIPHERED_KEY                = "KEY_CIPHERED_KEY"
KEY_SESSION_ORIGIN_IDX          = "KEY_SESSION_ORIGIN_IDX"
KEY_CIPHERED_PLAYER_IDX         = "KEY_CIPHERED_PLAYER_IDX"
KEY_SESSION                     = "KEY_SESSION"
KEY_ACTION                      = "KEY_ACTION"
KEY_PUB_CERT                    = "KEY_PUB_CERT"
KEY_USERNAME                    = "KEY_USERNAME"
KEY_IDENTIFICATION              = "KEY_IDENTIFICATION"
KEY_CLIENT_PUBLIC_KEY           = "KEY_CLIENT_PUBLIC_KEY"
KEY_CITIZEN_CARD_INFO           = "KEY_CITIZEN_CARD_INFO"
KEY_DECK                        = "KEY_DECK"
KEY_DECK_COUNT                  = "KEY_DECK_COUNT"
KEY_NEXT_PLAYER_PUB_KEY         = "KEY_NEXT_PLAYER_PUB_KEY"
KEY_NEXT_PLAYER_IDX             = "KEY_NEXT_PLAYER_IDX"
KEY_PLAYER_IDX                  = "KEY_PLAYER_IDX"
KEY_SEND_TO_PLAYER_IDX          = "KEY_SEND_TO_PLAYER_IDX"
KEY_PUB_KEY_IDX_0               = "KEY_PUB_KEY_IDX_0"
KEY_PUB_KEY_IDX_1               = "KEY_PUB_KEY_IDX_1"
KEY_PUB_KEY_IDX_2               = "KEY_PUB_KEY_IDX_2"
KEY_PUB_KEY_IDX_3               = "KEY_PUB_KEY_IDX_3"
KEY_DECK_CYPHER                 = "KEY_DECK_CYPHER"
KEY_CYPHER_ARRAY                = "KEY_CYPHER_ARRAY"
KEY_START_PLAYER                = "KEY_START_PLAYER"
KEY_PLAY_CARD                   = "KEY_PLAY_CARD"
KEY_PLAY_CURRENT_HAND           = "KEY_PLAY_CURRENT_HAND"
KEY_PLAY_FIRST_PLAYER           = "KEY_PLAY_FIRST_PLAYER"
KEY_BIT_COMMITMENT              = "KEY_BIT_COMMITMENT"
KEY_USE_CC                      = "KEY_USE_CC"    
KEY_SIGNED_DATA                 = "KEY_SIGNED_DATA"
KEY_CERTIFICATE                 = "KEY_CERTIFICATE"
KEY_UNSIGNED_DATA               = "KEY_UNSIGNED_DATA"  
KEY_JOIN_TABLE                  = "KEY_JOIN_TABLE"    
KEY_R_ONE                       = "KEY_R_ONE"
KEY_R_TWO                       = "KEY_R_TWO"
KEY_CIPHERED_HAND               = "KEY_CIPHERED_HAND" 
KEY_UNSIGNED_CONTENT            = "KEY_UNSIGNED_CONTENT" 
KEY_SIGNED_CONTENT              = "KEY_SIGNED_CONTENT" 
KEY_IV                          = "KEY_IV"
KEY_HISTORY                     = "KEY_HISTORY"
KEY_HISTORY_POINTS              = "KEY_HISTORY_POINTS"
KEY_PLAYERS                     = "KEY_PLAYERS"

TABLE_STATUS_OPEN               = 0
TABLE_STATUS_GAME_START         = 1
TABLE_STATUS_GAME_END           = 2