#JSON KEYS

KEY_CIPHERED_SYMM_KEY = "ciphered_symm_key"
KEY_CIPHERED_CONTENT = "ciphered_content"
#INTERNAL KEYS
USER_ORIGIN = "userO"
USER_DESTINATION = "userD"


#CLIENT TO SERVER 





SEND_DECK_TO_SESSION_PLAYER = 1
DECK_SENT_TO_SESSION_PLAYER = 2

#GENERIC
BUFFER_SIZE_CLIENT      = 65520
BUFFER_SIZE_SERVER      = 65520
SERVER_PORT             = 3000



#SERVER TO CLIENT
SEND_PUBLIC_KEY         = "SEND_PUBLIC_KEY"
WAIT                    = "WAIT"
NO_PENDING_ACTIONS      = "NO_PENDING_ACTIONS"
SHUFFLE_DECK            = "SHUFFLE_DECK"
SHARE_PUB_KEYS          = "SHARE_PUB_KEYS"

#CLIENT TO SERVER 
LOGIN                        = "LOGIN"
EXCHANGE_PUBLIC_KEYS         = "EXCHANGE_PUBLIC_KEYS"
CHECK_PENDING_ACTIONS        = "CHECK_PENDING_ACTIONS"
SEND_DECK_TO_NEXT_PLAYER     = "SEND_DECK_TO_NEXT_PLAYER"
ACK_PUBLIC_KEYS              = "ACK_PUBLIC_KEYS"
DECK_SHUFFLED                = "DECK_SHUFFLED"



KEY_CIPHERED_CONTENT    = "KEY_CIPHERED_CONTENT" 
KEY_CIPHERED_KEY        = "KEY_CIPHERED_KEY"
KEY_CIPHERED_PLAYER_IDX = "KEY_CIPHERED_PLAYER_IDX"
KEY_SESSION             = "KEY_SESSION"
KEY_ACTION              = "KEY_ACTION"
KEY_PUB_CERT            = "KEY_PUB_CERT"
KEY_USERNAME            = "KEY_USERNAME"
KEY_CLIENT_PUBLIC_KEY   = "KEY_CLIENT_PUBLIC_KEY"
KEY_CITIZEN_CARD_INFO   = "KEY_CITIZEN_CARD_INFO"
KEY_DECK                = "KEY_DECK"
KEY_NEXT_PLAYER_PUB_KEY = "KEY_NEXT_PLAYER_PUB_KEY"
KEY_NEXT_PLAYER_IDX     = "KEY_NEXT_PLAYER_IDX"
KEY_PLAYER_IDX          = "KEY_PLAYER_IDX"
KEY_SEND_TO_PLAYER_IDX  = "KEY_SEND_TO_PLAYER_IDX"
KEY_PUB_KEY_IDX_0       = "KEY_PUB_KEY_IDX_0"
KEY_PUB_KEY_IDX_1       = "KEY_PUB_KEY_IDX_1"
KEY_PUB_KEY_IDX_2       = "KEY_PUB_KEY_IDX_2"
KEY_PUB_KEY_IDX_3       = "KEY_PUB_KEY_IDX_3"

TABLE_STATUS_OPEN       = 0
TABLE_STATUS_GAME_START = 1
TABLE_STATUS_GAME_END   = 2

TABLE_NUMBER_OF_PLAYERS = 4  


SOCKET_TIMEOUT          = 10
SOCKET_IDLE_LIMIT       = 500